source "https://rubygems.org"
gem 'pg'
gem 'dm-postgres-adapter'
gem 'do_postgres'
gem 'dm-core', '~>1.0'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-is-list'
gem 'dm-validations'
gem 'json', '~>1.0'
gem 'sinatra', '~>1.0'
gem 'thin'
gem 'permutation'
gem 'haml'
gem 'rest-client'
gem 'syntax'
gem 'maruku'
