insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("bed", "I took a nap.", "nap.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("bicyle", "Saw someone put a bike on the bus..", "bike.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("books", "I read a book.", "book.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("briefcase", "I went to work.", "work.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("cell phone", "I talked on the phone.", "phone.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("cocktail glass", "I went to a bar.", "drink.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("earphones", "I listened to music.", "Music.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("envelope", "I used e-mail.", "email.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("home", "I went home.", "home.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("man with text bubble", "I spoke with the bus driver.", "busdriver.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("shopping basket", "I went shopping.", "shopping.gif", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("transit pass", "I used my getDowntown&reg; transit pass.", "go-pass-0910_front.jpg", 1);
insert into "bus_bingo_tile_templates" ("title", "alt", "image_filename", "enabled") values ("two businessmen", "I had a conversation.", "conversation.gif", 1);
